# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: llm.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tllm.proto\x12\x03llm\"\x1b\n\nLLMRequest\x12\r\n\x05query\x18\x01 \x01(\t\"\x1c\n\x08LLMReply\x12\x10\n\x08response\x18\x01 \x01(\t20\n\x03LLM\x12)\n\x05query\x12\x0f.llm.LLMRequest\x1a\r.llm.LLMReply\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'llm_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _LLMREQUEST._serialized_start=18
  _LLMREQUEST._serialized_end=45
  _LLMREPLY._serialized_start=47
  _LLMREPLY._serialized_end=75
  _LLM._serialized_start=77
  _LLM._serialized_end=125
# @@protoc_insertion_point(module_scope)
